SELECT nombre FROM producto;
SELECT nombre,precio FROM producto;
SELECT * FROM producto;
SELECT nombre,CONCAT('€',FORMAT(precio,2,'DE_DE')) ,CONCAT('$',FORMAT(precio,2,'EN_US'))  FROM producto;
SELECT nombre AS "Nom De producte",CONCAT('€',FORMAT(precio,2,'DE_DE')) AS "EUROS" ,CONCAT('$',FORMAT(precio,2,'EN_US')) AS "DÒLARS" FROM producto;
SELECT UPPER(nombre) AS nombre ,precio FROM producto;
SELECT LOWER(nombre) AS nombre ,precio FROM producto;
SELECT nombre ,  UPPER(SUBSTR(nombre, 1, 2)) AS CoDI FROM fabricante;
SELECT nombre,ROUND(precio) AS "precio redondeado" FROM producto;
SELECT nombre,SUBSTRING_INDEX(precio, ".", 1) AS "precio redondo" FROM producto;
SELECT fabricante.nombre FROM fabricante  INNER JOIN producto ON fabricante.codigo = producto.codigo_fabricante;
SELECT fabricante.nombre FROM fabricante  INNER JOIN producto ON fabricante.codigo = producto.codigo_fabricante GROUP BY (fabricante.nombre);
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio,nombre LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC,nombre LIMIT 1;
SELECT producto.nombre AS "nombre producto" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.codigo = 2;
SELECT producto.nombre ,precio,fabricante.nombre as "fabricante" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre ,precio,fabricante.nombre as "fabricante" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY fabricante.nombre;
SELECT producto.codigo AS "CÓDigo", producto.nombre AS "producto", fabricante.codigo "codigo",fabricante.nombre as "fabricante" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre, precio AS "precio más bArato",fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY producto.precio aSC LImIT 1 ;
SELECT producto.nombre, precio AS "precio Más barAto",fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY producto.precio DesC LIMIT 1 ;
SELECT * FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = "Lenovo";
SELECT * FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = "Crucial" WHERE precio > 200;
SELECT * FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo WHERE ( fabricante.nombre = "Asus" Or fabricante.nombre = "Hewlett-PAckard" or fabricante.nombre = "Seagate" );
SELECT * FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo WHERE  fabricante.nombre IN( "Asus" , "Hewlett-Packard" , "Seagate" );
SELECT producto.nombre,producto.precio FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo WHERE SUBSTRING(fabricante.nombre,CHAR_LENGTH(fabricante.nombre),1) = "E";
SELECT producto.nombre,producto.precio  FROM producto INNER JOIN fabricante On producto.codigo_fabricante = fabricante.codigo WHERE  POSITION("w" IN fabricante.nombre) ;
SELECT producto.nombre,producto.precio ,fabricante.nombre aS "fabricante" FROM producto INNER JOIN fabricante oN producto.codigo_fabricante = fabricante.codigo WHERE producto.precio >=180 ORDER BY producto.precio desc, producto.nombre asc; 
SELECT fabricante.codigo,fabricante.nombre  FROM fabricante INNER JOIN producto ON fabricante.codigo = producto.codigo_fabricante Group by fabricante.codigo,fabricante.nombre ;
SELECT fabricante.codigo,fabricante.nombre, producto.nombre  FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante groUp by fabricante.codigo,fabricante.nombre ,producto.nombre;
SELECT fabricante.codigo,fabricante.nombre FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante WHERE producto.nombre is nUll grouP bY fabricante.codigo,fabricante.nombre ,producto.nombre;
SELECT producto.nombre FROM producto WHERE codigo_fabricante in (SELECT codigo FROM fabricante WHERE nombre = "Lenovo");
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante in (SELECT codigo FROM fabricante WHERE nombre = "Lenovo"));
SELECT producto.nombre  FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = "Lenovo" ORDER BY producto.precio desc lImit 1;  
SELECT producto.nombre  FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = "Hewlett-Packard" ORDER BY producto.precio asc limit 1;  
SELECT * FROM producto WHERE precio >= (SELECT MAX(precio) FROM producto WHERE codigo_fabricante in (SELECT codigo FROM fabricante WHERE nombre = "Lenovo"));
SELECT * FROM producto WHERE precio > (SELECT AVG(precio) FROM producto WHERE codigo_fabricante in (SELECT codigo FROM fabricante WHERE nombre = "Asus")) AND codigo_fabricante in (SELECT codigo FROM fabricante WHERE nombre = "Asus");

