SELECT nombre FROM producto;
SELECT nombre,precio FROM producto;
SELECT * FROM producto;
SELECT nombre,CONCAT('€',FORMAT(precio,2,'DE_DE')) ,CONCAT('$',FORMAT(precio,2,'EN_US'))  FROM producto;
SELECT nombre AS "Product name",CONCAT('€',FORMAT(precio,2,'DE_DE')) AS "EUROS" ,CONCAT('$',FORMAT(precio,2,'EN_US')) AS "DÒLARS" FROM producto;
SELECT UPPER(nombre) AS nombre ,precio FROM producto;
SELECT LOWER(nombre) AS nombre ,precio FROM producto;
SELECT nombre, UPPER(SUBSTR(nombre, 1, 2)) AS "Code" FROM fabricante;
SELECT nombre, ROUND(precio) AS "Rounded price" FROM producto;
SELECT nombre, SUBSTRING_INDEX(precio, ".", 1) AS "Round price" FROM producto;
SELECT fabricante.nombre FROM fabricante  INNER JOIN producto ON fabricante.codigo = producto.codigo_fabricante;
SELECT fabricante.nombre FROM fabricante  INNER JOIN producto ON fabricante.codigo = producto.codigo_fabricante GROUP BY (fabricante.nombre);
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio,nombre LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC,nombre LIMIT 1;
SELECT producto.nombre AS "Product name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.codigo = 2;
SELECT producto.nombre ,precio,fabricante.nombre AS "Manufacturer" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre ,precio,fabricante.nombre AS "Manufacturer" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY fabricante.nombre;
SELECT producto.codigo AS "Code", producto.nombre AS "Product", fabricante.codigo AS "Code",fabricante.nombre AS "Manufacturer" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre, precio AS "Lowest price",fabricante.nombre AS "Manufacturer" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY producto.precio aSC LImIT 1 ;
SELECT producto.nombre, precio AS "Lowest price",fabricante.nombre AS "Manufacturer" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY producto.precio DesC LIMIT 1 ;
SELECT * FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = "Lenovo";
SELECT * FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = "Crucial" WHERE precio > 200;
SELECT * FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo WHERE ( fabricante.nombre = "Asus" Or fabricante.nombre = "Hewlett-PAckard" or fabricante.nombre = "Seagate" );
SELECT * FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo WHERE  fabricante.nombre IN( "Asus" , "Hewlett-Packard" , "Seagate" );
SELECT producto.nombre,producto.precio FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo WHERE SUBSTRING(fabricante.nombre,CHAR_LENGTH(fabricante.nombre),1) = "E";
SELECT producto.nombre,producto.precio  FROM producto INNER JOIN fabricante On producto.codigo_fabricante = fabricante.codigo WHERE  POSITION("w" IN fabricante.nombre) ;
SELECT producto.nombre,producto.precio ,fabricante.nombre AS "Manufacturer" FROM producto INNER JOIN fabricante oN producto.codigo_fabricante = fabricante.codigo WHERE producto.precio >=180 ORDER BY producto.precio desc, producto.nombre asc; 
SELECT fabricante.codigo,fabricante.nombre  FROM fabricante INNER JOIN producto ON fabricante.codigo = producto.codigo_fabricante Group by fabricante.codigo,fabricante.nombre ;
SELECT fabricante.codigo,fabricante.nombre, producto.nombre  FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante groUp by fabricante.codigo,fabricante.nombre ,producto.nombre;
SELECT fabricante.codigo,fabricante.nombre FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante WHERE producto.nombre IS NULL grouP bY fabricante.codigo,fabricante.nombre ,producto.nombre;
SELECT producto.nombre FROM producto WHERE codigo_fabricante in (SELECT codigo FROM fabricante WHERE nombre = "Lenovo");
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante in (SELECT codigo FROM fabricante WHERE nombre = "Lenovo"));
SELECT producto.nombre  FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = "Lenovo" ORDER BY producto.precio desc lImit 1;  
SELECT producto.nombre  FROM producto INNER JOIN fabricante on producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = "Hewlett-Packard" ORDER BY producto.precio asc limit 1;  
SELECT * FROM producto WHERE precio >= (SELECT MAX(precio) FROM producto WHERE codigo_fabricante in (SELECT codigo FROM fabricante WHERE nombre = "Lenovo"));
SELECT * FROM producto WHERE precio > (SELECT AVG(precio) FROM producto WHERE codigo_fabricante in (SELECT codigo FROM fabricante WHERE nombre = "Asus")) AND codigo_fabricante in (SELECT codigo FROM fabricante WHERE nombre = "Asus");
SELECT apellido1,apellido2,nombre  FROM persona WHERE tipo = "alumno" order by apellido1 asc,apellido2 asc,nombre asc;
SELECT apellido1,apellido2,nombre  FROM persona WHERE tipo = "alumno" AND telefono IS NULL;
SELECT  apellido1,apellido2,nombre  FROM persona WHERE tipo = "alumno" AND YEAR(fecha_nacimiento) = 1999; 
SELECT apellido1,apellido2,nombre,nif  FROM persona WHERE tipo = "profesor" AND telefono IS NULL AND SUBSTRING(nif,LENGTH(nif) ,1) = "k";
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT persona.apellido1,persona.apellido2,persona.nombre,departamento.nombre AS "Name" FROM profesor INNER JOIN departamento on profesor.id_departamento = departamento.id INNER JOIN persona on profesor.id_profesor = persona.id AND persona.tipo = "profesor" order by persona.apellido1 asc,persona.apellido2 asc,persona.nombre asc;
SELECT asignatura.nombre AS "Subject",curso_escolar.anyo_inicio AS "Start year" , curso_escolar.anyo_fin AS "año fin" FROM asignatura INNER JOIN alumno_se_matricula_asignatura on asignatura.id = alumno_se_matricula_asignatura.id_asignatura INNER JOIN persona on persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN curso_escolar on alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE persona.tipo = "alumno" AND persona.nif ="26902806M";
SELECT departamento.nombre FROM departamento INNER JOIN profesor on departamento.id = profesor.id_departamento INNER JOIN asignatura on profesor.id_profesor = asignatura.id_profesor INNER JOIN grado on grado.id = asignatura.id_grado WHERE grado.nombre ="Grado en Ingeniería Informática (Plan 2015)" group by departamento.nombre;
SELECT persona.apellido1,persona.apellido2,persona.nombre FROM persona INNER JOIN alumno_se_matricula_asignatura on persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN curso_escolar on alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE curso_escolar.anyo_inicio >= 2018 AND curso_escolar.anyo_fin <= 2019 AND persona.tipo = "alumno" group by persona.id;
SELECT departamento.nombre as"Department",persona.apellido1 AS "First surname",persona.apellido2 AS "Second surname", persona.nombre AS "Name" FROM departamento LEFT JOIN profesor on profesor.id_departamento = departamento.id LEFT JOIN persona on profesor.id_profesor = persona.id AND persona.tipo = "profesor" order by departamento.nombre asc,persona.apellido1 asc, persona.apellido2 asc, persona.nombre ;
SELECT persona.apellido1 AS "First surname",persona.apellido2 AS "Second surname", persona.nombre AS "Name" FROM departamento INNER JOIN profesor on departamento.id = profesor.id_departamento right join persona on persona.id = profesor.id_profesor WHERE profesor.id_profesor IS NULL AND persona.tipo = "profesor";
SELECT departamento.id, departamento.nombre as"Departamento" FROM departamento LEFT JOIN profesor on departamento.id = profesor.id_departamento WHERE id_profesor IS NULL;
SELECT * FROM persona WHERE id IN (SELECT profesor.id_profesor FROM profesor LEFT JOIN asignatura on profesor.id_profesor = asignatura.id_profesor WHERE asignatura.id_profesor IS NULL);
SELECT asignatura.* FROM asignatura LEFT JOIN profesor on asignatura.id_profesor = profesor.id_profesor WHERE asignatura.id_profesor IS NULL;
SELECT departamento.* FROM departamento INNER JOIN profesor on departamento.id = profesor.id_departamento LEFT JOIN asignatura on profesor.id_profesor = asignatura.id_profesor WHERE asignatura.id IS NULL group by departamento.id;
SELECT apellido1,apellido2,nombre  FROM persona WHERE tipo = "alumno" ORDER BY apellido1 asc,apellido2 asc,nombre asc;
SELECT apellido1,apellido2,nombre  FROM persona WHERE tipo = "alumno" AND telefono IS NULL;
SELECT  apellido1,apellido2,nombre  FROM persona WHERE tipo = "alumno" AND YEAR(fecha_nacimiento) = 1999; 
SELECT apellido1,apellido2,nombre,nif  FROM persona WHERE tipo = "profesor" AND telefono IS NULL AND SUBSTRING(nif,LENGTH(nif) ,1) = "k";
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT persona.apellido1,persona.apellido2,persona.nombre,departamento.nombre AS "Name" FROM profesor  INNER JOIN departamento ON profesor.id_departamento = departamento.id  INNER JOIN persona ON profesor.id_profesor = persona.id AND persona.tipo = "profesor" ORDER BY persona.apellido1 asc,persona.apellido2 asc,persona.nombre asc;
SELECT asignatura.nombre AS "Subject",curso_escolar.anyo_inicio AS "Start year" , curso_escolar.anyo_fin AS "Finish year" FROM asignatura  INNER JOIN alumno_se_matricula_asignatura ON asignatura.id = alumno_se_matricula_asignatura.id_asignatura  INNER JOIN persona ON persona.id = alumno_se_matricula_asignatura.id_alumno  INNER JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE persona.tipo = "alumno" AND persona.nif ="26902806M";
SELECT departamento.nombre FROM departamento INNER JOIN profesor ON departamento.id = profesor.id_departamento  INNER JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor  INNER JOIN grado ON grado.id = asignatura.id_grado WHERE grado.nombre ="Grado en Ingeniería Informática (Plan 2015)"  GROUP BY departamento.nombre;
SELECT persona.apellido1,persona.apellido2,persona.nombre FROM persona  INNER JOIN alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno  INNER JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE curso_escolar.anyo_inicio >= 2018 AND curso_escolar.anyo_fin <= 2019 AND persona.tipo = "alumno"  GROUP BY persona.id;
SELECT departamento.nombre AS "Department",persona.apellido1 AS "First surname",persona.apellido2 AS "Second surname", persona.nombre AS "Name" FROM departamento  LEFT JOIN profesor ON profesor.id_departamento = departamento.id  LEFT JOIN persona ON profesor.id_profesor = persona.id AND persona.tipo = "profesor" ORDER BY departamento.nombre asc,persona.apellido1 asc, persona.apellido2 asc, persona.nombre ;
SELECT persona.apellido1 AS "First surname",persona.apellido2 AS "Second surname", persona.nombre AS "Name" FROM departamento  INNER JOIN profesor ON departamento.id = profesor.id_departamento right join persona ON persona.id = profesor.id_profesor WHERE profesor.id_profesor IS NULL AND persona.tipo = "profesor";
SELECT departamento.id, departamento.nombre AS "Department" FROM departamento  LEFT JOIN profesor ON departamento.id = profesor.id_departamento WHERE id_profesor IS NULL;
SELECT * FROM persona WHERE id in(SELECT profesor.id_profesor FROM profesor  LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE asignatura.id_profesor IS NULL);
SELECT asignatura.* FROM asignatura  LEFT JOIN profesor ON asignatura.id_profesor = profesor.id_profesor WHERE asignatura.id_profesor IS NULL;
SELECT departamento.* FROM departamento  INNER JOIN profesor ON departamento.id = profesor.id_departamento  LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE asignatura.id IS NULL  GROUP BY departamento.id;
SELECT COUNT(id) AS "Total students" FROM persona WHERE tipo = "alumno";
SELECT COUNT(id) AS "Total students from ' 99" FROM persona WHERE tipo = "alumno" AND YEAR(fecha_nacimiento) = 1999;
SELECT departamento.nombre, COUNT(profesor.id_departamento) AS "Total teachers" FROM departamento INNER JOIN profesor ON departamento.id = profesor.id_departamento  GROUP BY departamento.nombre ORDER BY COUNT(profesor.id_departamento) desc;
SELECT departamento.nombre ,COUNT(DISTINCT profesor.id_profesor) AS "Total teachers" FROM departamento  LEFT JOIN profesor ON departamento.id = profesor.id_departamento  GROUP BY departamento.nombre ORDER BY COUNT(DISTINCT profesor.id_profesor);
SELECT grado.nombre, COUNT(DISTINCT asignatura.id)  AS "Total subjects" FROM grado  LEFT JOIN asignatura ON grado.id = asignatura.id_grado  GROUP BY grado.nombre ORDER BY COUNT(DISTINCT asignatura.id) desc;
SELECT grado.nombre, COUNT(DISTINCT asignatura.id)  AS "Total subjects" FROM grado  LEFT JOIN asignatura ON grado.id = asignatura.id_grado  GROUP BY grado.nombre having COUNT(DISTINCT asignatura.id)  > 40 ORDER BY COUNT(DISTINCT asignatura.id) desc ;
SELECT grado.nombre AS "Degree", asignatura.tipo AS "Subjects type", sum(asignatura.creditos) AS "Total credits" FROM grado  INNER JOIN asignatura ON grado.id = asignatura.id_grado  GROUP BY asignatura.tipo, grado.nombre ;
SELECT curso_escolar.anyo_inicio AS "Course" , COUNT(alumno_se_matricula_asignatura.id_alumno) AS "Total students" FROM alumno_se_matricula_asignatura  INNER JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id   GROUP BY curso_escolar.id ;
SELECT persona.id, persona.apellido1 AS "First surname",persona.apellido2 AS "Second surname", persona.nombre AS "Name" ,count(asignatura.id)  AS "Total subjects" FROM persona  INNER JOIN profesor ON persona.id = profesor.id_profesor  LEFT JOIN asignatura ON  profesor.id_profesor = asignatura.id_profesor  GROUP BY persona.id ORDER BY COUNT(asignatura.id) desc;
SELECT fecha_nacimiento,persona.apellido1 AS "First surname",persona.apellido2 AS "Second surname", persona.nombre AS "Name" FROM persona WHERE TO_DAYS(persona.fecha_nacimiento) >= (SELECT max(TO_DAYS(persona.fecha_nacimiento)) FROM persona WHERE tipo = "Alumno") and tipo = "Alumno";
SELECT persona.apellido1 AS "First surname",persona.apellido2 AS "Second surname", persona.nombre AS "Name", departamento.nombre AS "Department" FROM persona  INNER JOIN profesor ON persona.id = profesor.id_profesor  INNER JOIN departamento ON profesor.id_departamento = departamento.id  LEFT JOIN asignatura ON asignatura.id_profesor = profesor.id_profesor WHERE asignatura.id IS NULL AND persona.tipo = "Profesor" ;
